stages:
  - build

build-job:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -f Dockerfile.train -t iris-train-image .
    - docker build -f Dockerfile.api -t iris-api-image .

