# Dockerfile.api
FROM python:3.10-slim

WORKDIR /app

COPY requirements_api.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY model.pkl ./model.pkl

COPY . .

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]

