name: ML Project CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build training image
        run: docker build -f Dockerfile.train -t iris-train-image .

      - name: Build API image
        run: docker build -f Dockerfile.api -t iris-api-image .

